-- Wilkipedia database schema.
-- Paste this whole file into Supabase → SQL Editor → New query → Run.
-- Safe to run once on a fresh project. After it, run seed.sql (generated by tools/build.py).
--
-- Security model: the browser only ever holds the public "anon/publishable" key,
-- so every rule that matters is enforced here with row-level security (RLS),
-- never in the JavaScript.

-- ───────────────────────── profiles ─────────────────────────
create table public.profiles (
  id           uuid primary key references auth.users on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 40),
  role         text not null default 'contributor'
               check (role in ('contributor', 'trusted', 'reviewer', 'admin')),
  school_verified boolean not null default false,       -- signed in with an @scusd.net account
  -- Profile pictures come from a fixed set of icons + colours, never uploads.
  -- Keys must match AVATARS / AVATAR_COLORS in assets/js/ui.js.
  avatar       text check (avatar in ('fox', 'panda', 'tiger', 'owl', 'turtle', 'octopus',
               'frog', 'penguin', 'cat', 'dog', 'koala', 'bee', 'bolt', 'rocket', 'books', 'flask',
               'palette', 'music', 'ball', 'star')),
  avatar_color text not null default 'green' check (avatar_color in
               ('green', 'blue', 'purple', 'red', 'orange', 'teal', 'pink', 'gray')),
  grad_year    int check (grad_year between 2020 and 2040),
  show_on_leaderboard boolean not null default true,
  created_at   timestamptz not null default now()
);

-- Every new sign-in gets a profile. Display name defaults to the Google first
-- name only, so a full name is never published without the student choosing it.
-- An @scusd.net account earns the school badge; the email itself is never shown.
create function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name, school_verified)
  values (new.id,
          left(coalesce(
            nullif(split_part(new.raw_user_meta_data->>'full_name', ' ', 1), ''),
            split_part(new.email, '@', 1)), 40),
          lower(coalesce(new.email, '')) like '%@scusd.net');
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create function public.my_role() returns text
language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid()
$$;

create function public.is_reviewer() returns boolean
language sql stable security definer set search_path = public as $$
  select coalesce(public.my_role() in ('reviewer', 'admin'), false)
$$;

-- Only admins run the bounty board
create function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select coalesce(public.my_role() = 'admin', false)
$$;

alter table public.profiles enable row level security;
create policy "profiles are public" on public.profiles for select using (true);
create policy "edit own profile" on public.profiles for update using (id = auth.uid());
-- Users may change their own profile settings and nothing else. Roles and the
-- school badge are changed only by an admin in the Supabase table editor.
revoke update on public.profiles from authenticated;
grant update (display_name, avatar, avatar_color, grad_year, show_on_leaderboard)
  on public.profiles to authenticated;

-- ───────────────────────── bounties ─────────────────────────
create table public.bounties (
  id          text primary key,                       -- e.g. SCI-04
  title       text not null,
  track       text not null,
  course_slug text,
  teacher     text,
  kind        text,                                   -- suggested submission kind
  size        text not null check (size in ('S', 'M', 'L')),
  priority    int  not null default 3 check (priority between 1 and 5),
  you_get     text,
  done_means  text,
  due_on      date,                                   -- optional deadline (the Agenda view)
  status      text not null default 'open' check (status in ('open', 'done', 'closed')),
  closed_at   timestamptz,                            -- set when it leaves the board (the Ledger)
  created_at  timestamptz not null default now()
);

-- done = completed, closed = withdrawn; either stamps closed_at, reposting clears it
create function public.on_bounty_status() returns trigger
language plpgsql as $$
begin
  if new.status is distinct from old.status then
    new.closed_at := case when new.status = 'open' then null else now() end;
  end if;
  return new;
end $$;
create trigger bounties_status before update of status on public.bounties
  for each row execute function public.on_bounty_status();

alter table public.bounties enable row level security;
-- The bounty board belongs to the review team: they see and claim, admins run it
create policy "review team sees bounties" on public.bounties for select using (public.is_reviewer());
create policy "admins post bounties" on public.bounties for insert with check (public.is_admin());
create policy "admins edit bounties" on public.bounties for update using (public.is_admin());
create policy "admins delete bounties" on public.bounties for delete using (public.is_admin());

-- ───────────────────────── claims ─────────────────────────
-- A claim lasts 14 days. Expired claims are simply ignored when read.
create table public.claims (
  bounty_id  text not null references public.bounties on delete cascade,
  user_id    uuid not null default auth.uid() references public.profiles on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default now() + interval '14 days',
  primary key (bounty_id, user_id)
);

alter table public.claims enable row level security;
create policy "review team sees claims" on public.claims for select using (public.is_reviewer());
create policy "review team claims" on public.claims for insert
  with check (user_id = auth.uid() and public.is_reviewer()
              and exists (select 1 from public.bounties b where b.id = bounty_id and b.status = 'open'));
create policy "drop your own claim" on public.claims for delete using (user_id = auth.uid());

-- The client can't pick its own timer. To renew, drop the claim and claim again.
create function public.on_claim_insert() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  new.user_id := auth.uid();
  new.created_at := now();
  new.expires_at := now() + interval '14 days';
  delete from public.claims where bounty_id = new.bounty_id and user_id = new.user_id;
  return new;
end $$;

create trigger claims_insert before insert on public.claims
  for each row execute function public.on_claim_insert();

-- ───────────────────────── submissions ─────────────────────────
-- One table holds everything students contribute. A submission becomes public
-- content the moment a reviewer sets status = 'approved'. Work outlives its
-- author's account: deleting a profile leaves user_id null ("Former student").
create table public.submissions (
  id          bigint generated always as identity primary key,
  user_id     uuid default auth.uid() references public.profiles on delete set null,
  bounty_id   text references public.bounties on delete set null,
  course_slug text,                                   -- null for school-wide info
  kind        text not null check (kind in
              ('course_overview', 'teacher_section', 'resource', 'tip', 'summer_hw', 'school_info',
               'club', 'sport')),
  teacher     text,
  payload     jsonb not null,
  status      text not null default 'pending'
              check (status in ('pending', 'approved', 'changes', 'rejected')),
  review_note text,
  reviewed_by uuid references public.profiles on delete set null,
  reviewed_at timestamptz,
  created_at  timestamptz not null default now()
);
create index on public.submissions (course_slug, status);

alter table public.submissions enable row level security;
create policy "approved is public, own and reviewers see all" on public.submissions for select
  using (status = 'approved' or user_id = auth.uid() or public.is_reviewer());
create policy "submit as yourself" on public.submissions for insert
  with check (user_id = auth.uid() and status = 'pending'
              and reviewed_by is null and reviewed_at is null and review_note is null);
create policy "reviewers review" on public.submissions for update using (public.is_reviewer());

-- Stamp the reviewer, and promote a contributor to trusted after 3 approvals.
create function public.on_review() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.status is distinct from old.status then
    new.reviewed_by := auth.uid();
    new.reviewed_at := now();
  end if;
  if new.status = 'approved' and old.status <> 'approved' then
    update public.profiles set role = 'trusted'
     where id = new.user_id and role = 'contributor'
       and (select count(*) from public.submissions
             where user_id = new.user_id and status = 'approved') >= 2;  -- this one makes 3
  end if;
  return new;
end $$;

create trigger submissions_review before update on public.submissions
  for each row execute function public.on_review();

-- ───────────────────────── comments ─────────────────────────
create table public.comments (
  id          bigint generated always as identity primary key,
  course_slug text not null,
  user_id     uuid default auth.uid() references public.profiles on delete set null,
  parent_id   bigint references public.comments on delete cascade,
  prompt      text,
  body        text not null check (char_length(body) between 1 and 2000),
  status      text not null default 'held' check (status in ('held', 'visible', 'hidden')),
  created_at  timestamptz not null default now()
);
create index on public.comments (course_slug, status);

-- Comments wait for approval unless the author is a reviewer, or is trusted
-- AND signed in with a school account. Personal accounts are always reviewed.
create function public.on_comment_insert() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  r text;
  school boolean;
begin
  select role, school_verified into r, school from public.profiles where id = auth.uid();
  new.user_id := auth.uid();
  new.created_at := now();
  new.status := case
    when r in ('reviewer', 'admin') then 'visible'
    when r = 'trusted' and school then 'visible'
    else 'held' end;
  return new;
end $$;

create trigger comments_insert before insert on public.comments
  for each row execute function public.on_comment_insert();

alter table public.comments enable row level security;
create policy "visible comments are public" on public.comments for select
  using (status = 'visible' or user_id = auth.uid() or public.is_reviewer());
create policy "signed-in users comment" on public.comments for insert
  with check (auth.uid() is not null);
create policy "reviewers moderate" on public.comments for update using (public.is_reviewer());
create policy "delete own or moderate" on public.comments for delete
  using (user_id = auth.uid() or public.is_reviewer());

create table public.comment_likes (
  comment_id bigint not null references public.comments on delete cascade,
  user_id    uuid not null default auth.uid() references public.profiles on delete cascade,
  primary key (comment_id, user_id)
);
alter table public.comment_likes enable row level security;
create policy "likes are public" on public.comment_likes for select using (true);
create policy "like as yourself" on public.comment_likes for insert with check (user_id = auth.uid());
create policy "unlike your own" on public.comment_likes for delete using (user_id = auth.uid());

-- ───────────────────────── reports ─────────────────────────
create table public.reports (
  id          bigint generated always as identity primary key,
  kind        text not null check (kind in ('outdated', 'inappropriate')),
  course_slug text,
  target      text not null,          -- 'overview', 'teacher:<name>', 'comment:<id>', 'school:<topic>' …
  note        text check (char_length(note) <= 1000),
  user_id     uuid not null default auth.uid() references public.profiles on delete cascade,
  resolved    boolean not null default false,
  created_at  timestamptz not null default now()
);

-- A reported comment is hidden until a reviewer looks at it.
create function public.on_report_insert() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  new.user_id := auth.uid();
  if new.kind = 'inappropriate' and new.target like 'comment:%' then
    update public.comments set status = 'hidden'
     where id = nullif(substring(new.target from 9), '')::bigint and status = 'visible';
  end if;
  return new;
end $$;

create trigger reports_insert before insert on public.reports
  for each row execute function public.on_report_insert();

alter table public.reports enable row level security;
create policy "reviewers read reports" on public.reports for select using (public.is_reviewer());
create policy "signed-in users report" on public.reports for insert with check (auth.uid() is not null);
create policy "reviewers resolve" on public.reports for update using (public.is_reviewer());

-- ───────────────────────── announcements ─────────────────────────
-- The bar under the header. Admins post; everyone sees the live ones
-- (active and not past ends_on, in Wilcox's time zone).
create table public.announcements (
  id         bigint generated always as identity primary key,
  kind       text not null default 'site' check (kind in ('school', 'site')),
  message    text not null check (char_length(message) between 3 and 280),
  link       text check (link is null or (char_length(link) <= 500 and link ~ '^(https?://|/)')),
  ends_on    date,
  active     boolean not null default true,
  created_by uuid default auth.uid() references public.profiles on delete set null,
  created_at timestamptz not null default now()
);
alter table public.announcements enable row level security;
create policy "live announcements are public" on public.announcements for select
  using ((active and (ends_on is null or ends_on >= (now() at time zone 'America/Los_Angeles')::date))
         or public.is_admin());
create policy "admins post announcements" on public.announcements for insert with check (public.is_admin());
create policy "admins edit announcements" on public.announcements for update using (public.is_admin());
create policy "admins delete announcements" on public.announcements for delete using (public.is_admin());

-- ───────────────────────── feedback ─────────────────────────
create table public.feedback (
  id         bigint generated always as identity primary key,
  kind       text not null check (kind in ('idea', 'bug', 'feature', 'other')),
  message    text not null check (char_length(message) between 3 and 2000),
  page       text check (char_length(page) <= 300),
  name       text check (char_length(name) <= 60),
  user_id    uuid default auth.uid() references public.profiles on delete set null,
  status     text not null default 'new' check (status in ('new', 'planned', 'done', 'closed')),
  created_at timestamptz not null default now()
);

create function public.on_feedback_insert() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  new.user_id := auth.uid();
  new.status := 'new';
  new.created_at := now();
  return new;
end $$;

create trigger feedback_insert before insert on public.feedback
  for each row execute function public.on_feedback_insert();

alter table public.feedback enable row level security;
create policy "anyone can send feedback" on public.feedback for insert to anon, authenticated with check (true);
create policy "reviewers read feedback" on public.feedback for select using (public.is_reviewer());
create policy "reviewers update feedback" on public.feedback for update using (public.is_reviewer());
create policy "reviewers delete feedback" on public.feedback for delete using (public.is_reviewer());

-- Names (only) of people whose feedback was marked done, for the Credits page
create view public.feedback_credits as
select name, count(*)::int as helped
  from public.feedback
 where status = 'done' and name is not null and btrim(name) <> ''
 group by name;

grant select on public.feedback_credits to anon, authenticated;

-- ───────────────────────── leaderboard ─────────────────────────
-- Points: a bounty pays once per person when their first submission for it is
-- approved (S 10, M 30, L 60). Each approved contribution outside a bounty is 5.
-- "Semester" starts Aug 1 or Jan 1.
create view public.leaderboard as
with pts as (
  select distinct on (s.user_id, coalesce(s.bounty_id, s.id::text))
         s.user_id, s.reviewed_at,
         case b.size when 'S' then 10 when 'M' then 30 when 'L' then 60 else 5 end as points
    from public.submissions s left join public.bounties b on b.id = s.bounty_id
   where s.status = 'approved'
   order by s.user_id, coalesce(s.bounty_id, s.id::text), s.reviewed_at
), subs as (
  select user_id, count(*)::int as approved
    from public.submissions where status = 'approved' group by user_id
)
select p.id, p.display_name, p.role,
       sum(pts.points)::int as points,
       coalesce(sum(pts.points) filter (where pts.reviewed_at >=
         date_trunc('year', now()) + case when extract(month from now()) >= 8
                                          then interval '7 months' else interval '0' end), 0)::int
         as semester_points,
       max(subs.approved) as approved,
       p.school_verified,
       p.avatar,
       p.avatar_color,
       p.grad_year
  from public.profiles p
  join pts on pts.user_id = p.id
  join subs on subs.user_id = p.id
 where p.show_on_leaderboard
 group by p.id;

grant select on public.leaderboard to anon, authenticated;

-- ───────────────────────── edits & notifications ─────────────────────────
alter table public.submissions
  add column edited_at timestamptz,
  add column edited_by uuid references public.profiles on delete set null;

create table public.submission_edits (
  id            bigint generated always as identity primary key,
  submission_id bigint not null references public.submissions on delete cascade,
  editor_id     uuid references public.profiles on delete set null,
  old_payload   jsonb not null,
  new_payload   jsonb not null,
  note          text not null check (char_length(note) between 1 and 500),
  created_at    timestamptz not null default now()
);
alter table public.submission_edits enable row level security;
create policy "author and reviewers read edits" on public.submission_edits for select
  using (public.is_reviewer()
         or exists (select 1 from public.submissions s where s.id = submission_id and s.user_id = auth.uid()));

create table public.notifications (
  id         bigint generated always as identity primary key,
  user_id    uuid not null references public.profiles on delete cascade,
  message    text not null,
  link       text,
  read       boolean not null default false,
  created_at timestamptz not null default now()
);
create index on public.notifications (user_id, read);
alter table public.notifications enable row level security;
create policy "read your own notifications" on public.notifications for select using (user_id = auth.uid());
create policy "mark your own as read" on public.notifications for update using (user_id = auth.uid());
create policy "delete your own notifications" on public.notifications for delete using (user_id = auth.uid());
revoke update on public.notifications from authenticated;
grant update (read) on public.notifications to authenticated;

-- Where a submission lives, for notification links (paths relative to the site root)
create function public.submission_link(s public.submissions) returns text
language sql immutable as $$
  select case
    when s.kind = 'club'  then 'clubs/'
    when s.kind = 'sport' then 'sports/'
    when s.course_slug is not null then 'courses/' || s.course_slug || '/'
    else 'school/' end
$$;

create function public.kind_label(k text) returns text
language sql immutable as $$
  select case k
    when 'course_overview' then 'course overview' when 'teacher_section' then 'teacher section'
    when 'resource' then 'resource' when 'tip' then 'tip' when 'summer_hw' then 'summer homework info'
    when 'school_info' then 'school info article' when 'club' then 'club info' when 'sport' then 'team info'
    else 'submission' end
$$;

create function public.edit_submission(p_id bigint, p_payload jsonb, p_note text) returns void
language plpgsql security definer set search_path = public as $$
declare
  s public.submissions;
  editor text;
begin
  if not public.is_reviewer() then raise exception 'Only reviewers can edit other people''s work'; end if;
  if coalesce(btrim(p_note), '') = '' then raise exception 'Say what you changed and why'; end if;
  select * into s from public.submissions where id = p_id for update;
  if not found then raise exception 'That submission no longer exists'; end if;

  insert into public.submission_edits (submission_id, editor_id, old_payload, new_payload, note)
  values (p_id, auth.uid(), s.payload, p_payload, btrim(p_note));
  update public.submissions set payload = p_payload, edited_at = now(), edited_by = auth.uid() where id = p_id;

  if s.user_id is not null and s.user_id <> auth.uid() then
    select display_name into editor from public.profiles where id = auth.uid();
    insert into public.notifications (user_id, message, link)
    values (s.user_id, format('%s (reviewer) edited your %s. Reason: %s', coalesce(editor, 'A reviewer'),
                              public.kind_label(s.kind), btrim(p_note)), public.submission_link(s));
  end if;
end $$;
grant execute on function public.edit_submission(bigint, jsonb, text) to authenticated;

-- Tell authors when a reviewer changes the status of their work
create function public.on_status_notify() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.status is distinct from old.status and new.user_id is not null and new.user_id <> coalesce(auth.uid(), '00000000-0000-0000-0000-000000000000') then
    insert into public.notifications (user_id, message, link)
    values (new.user_id,
      case
        when new.status = 'approved' then format('Your %s was published. Thank you!', public.kind_label(new.kind))
        when new.status = 'changes'  then format('A reviewer asked for changes to your %s: %s', public.kind_label(new.kind), coalesce(new.review_note, ''))
        when old.status = 'approved' then format('Your %s was unpublished. Reason: %s', public.kind_label(new.kind), coalesce(new.review_note, ''))
        else format('Your %s wasn''t accepted. Reason: %s', public.kind_label(new.kind), coalesce(new.review_note, ''))
      end,
      case when new.status = 'approved' then public.submission_link(new) else 'account/' end);
  end if;
  return new;
end $$;

create trigger submissions_notify after update of status on public.submissions
  for each row execute function public.on_status_notify();
