#!/usr/bin/env python3
"""Pulls Wilcox's official activities calendar into data/calendar.json.

    python3 tools/school_calendar.py [--file saved.csv]

The source is the "2026-2027 Wilcox Activities Calendar" Google Sheet that the
school links from its bell schedule page (SOURCE_PAGE). Nothing here is made
up: every event is a row of that sheet. This script only tidies it:
  - "Monday-Friday" / "Tuesday-Friday" rows become multi-day events;
  - each event gets a category (from its own wording) for the calendar's
    colours and filters;
  - Zoom meeting links are dropped (the event says "On Zoom"): they're fine on
    the school's own sheet, but reposting them publicly invites zoom-bombing.
Re-run it whenever the school updates the sheet, then run tools/build.py.

Standard library only.
"""

import csv
import io
import json
import re
import sys
import urllib.request
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "calendar.json"
SHEET = "https://docs.google.com/spreadsheets/d/1EokX2VyQlsmp5AojVMRaZDbtckmaU1mjlSwRpKSnhl0"
SOURCE_PAGE = "https://wilcox.santaclarausd.org/about/bell-schedule"
YEAR = "2026–27"

DAYS = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]

# (category, words in the event's own title that put it there), checked in order
CATEGORIES = [
    ("off", [r"no school", r"break\b", r"student holiday"]),
    ("milestone", [r"first day of school", r"first day of semester", r"end of quarter", r"end of semester",
                   r"^graduation$", r"seniors' last day"]),
    ("tests", [r"final", r"\bpsat\b", r"\bsat\b", r"caaspp", r"\bap (late )?testing"]),
    ("sports", [r"athletic season", r"football game"]),
    ("family", [r"parent", r"back to school night", r"open house", r"\belac\b", r"attendance matters",
                r"information night", r"summit", r"financial aid", r"college fair", r"ucla night", r"orientation",
                r"community college"]),
    ("arts", [r"concert", r"theatre", r"film festival", r"art expo", r"fashion show", r"showcase", r"orchestra",
              r"performance", r"cmea"]),
    ("spirit", [r"rally", r"homecoming", r"spirit", r"dance\b", r"ball\b", r"\bprom\b", r"quad night", r"\bbots\b",
                r"battle of the schools", r"fantastics", r"multicultural", r"skit night", r"send-off"]),
]
LABELS = {
    "off": "No school", "milestone": "School year", "tests": "Tests & finals", "sports": "Athletics",
    "family": "Families & info nights", "arts": "Arts & shows", "spirit": "Spirit & dances",
    "schedule": "Schedule change", "school": "Around school",
}


def category(title):
    t = title.lower()
    if "adjusted bell schedule" in t:
        return "schedule"
    for cat, pats in CATEGORIES:
        if any(re.search(p, t) for p in pats):
            return cat
    return "school"


def fetch(path=None):
    if path:
        return Path(path).read_text()
    req = urllib.request.Request(SHEET + "/export?format=csv", headers={"User-Agent": "wilkipedia/1.0 (wilcoxwiki.org)"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read().decode("utf-8")


def span(start, dayfield):
    """'Monday-Friday' on a Monday = five days; a single weekday = one day."""
    m = re.match(r"\s*(\w+)\s*-\s*(\w+)", dayfield or "")
    if not m or m.group(2).lower() not in DAYS:
        return start
    end = DAYS.index(m.group(2).lower())
    return start + timedelta(days=(end - start.weekday()) % 7)


def clean(s):
    return re.sub(r"\s+", " ", (s or "").strip())


def main():
    path = sys.argv[sys.argv.index("--file") + 1] if "--file" in sys.argv else None
    rows = list(csv.DictReader(io.StringIO(fetch(path))))
    events = []
    for r in rows:
        try:
            mo, d, y = (int(x) for x in r["Date"].strip().split("/"))
        except (ValueError, KeyError):
            continue
        start = date(y, mo, d)
        title = clean(r.get("Event"))
        if not title:
            continue
        where = clean(r.get("Location"))
        if "zoom.us" in where.lower():
            where = "On Zoom"
        when = clean(r.get("Time"))
        if when.lower() in ("no school", "all day"):
            when = ""
        events.append({
            "start": start.isoformat(), "end": span(start, r.get("Day")).isoformat(),
            "title": title, "time": when, "where": where, "cat": category(title),
        })
    events.sort(key=lambda e: (e["start"], e["cat"] != "off", e["title"]))
    out = {
        "_about": "GENERATED by tools/school_calendar.py from Wilcox's official activities calendar (source). Don't edit; re-run it.",
        "source": SHEET, "sourcePage": SOURCE_PAGE, "year": YEAR, "labels": LABELS, "events": events,
    }
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=1))
    cats = {}
    for e in events:
        cats[e["cat"]] = cats.get(e["cat"], 0) + 1
    print(f"wrote {OUT.relative_to(ROOT)}: {len(events)} events {cats}")


if __name__ == "__main__":
    main()
